/**
 * @module email
 *
 * Public surface for the email module. Outsiders MUST import from
 * `@/modules/email` — never reach into `./service` directly.
 */
export {
  OPS_EMAIL,
  sendVerificationEmail,
  sendMobileVerificationCode,
  sendMobilePasswordResetCode,
  sendPasswordResetEmail,
  sendTenderSubmittedEmail,
  sendTenderSubmittedBuilderEmail,
  sendTenderSubmittedOpsEmail,
  sendTenderShortlistedEmail,
  sendTenderAwardedEmail,
  sendTenderRejectedEmail,
  sendTenderWithdrawnEmail,
  sendBuilderTenderInvitationEmail,
  sendParticipantInviteEmail,
  sendParticipantJoinedEmail,
  sendRoundAwardedNoticeEmail,
  sendTenderValidityExpiringEmail,
  sendScopeReadyEmail,
  sendScopeAddendumEmail,
  sendScopeRunOpsEmail,
  sendOwnerSignupOpsEmail,
  sendBuilderSignupOpsEmail,
  sendArchitectSignupOpsEmail,
  sendBuilderApprovedEmail,
  sendProjectPublishedOwnerEmail,
  sendProjectPublishedBuilderEmail,
  sendProjectPublishedOpsEmail,
  sendUnlockOwnerEmail,
  sendUnlockBuilderEmail,
  sendUnlockOpsEmail,
  sendLaunchInviteEmail,
  sendGuideDownloadEmail,
  sendGuideLeadOpsEmail,
  sendOwnerAdvisoryOpsEmail,
  sendOwnerAdvisoryConfirmationEmail,
  sendEstimateRequestOpsEmail,
  sendMetaLeadOpsEmail,
  sendMetaLeadUnretrievableEmail,
  sendBookCallOpsEmail,
  sendArchitectTenderOpsEmail,
  sendArchitectTenderConfirmationEmail,
  sendPartnerInterestOpsEmail,
  sendPartnerInterestConfirmationEmail,
  sendPartnerIntroOpsEmail,
  sendPartnerIntroConfirmationEmail,
  sendAdsFunnelMagicLinkEmail,
  sendAuthSigninLinkEmail,
} from "./service";
